backend:
  name: git-gateway
  branch: main

media_folder: src/static/img
public_folder: /img

site_url: https://example.netlify.app
logo_url: https://example.netlify.app/logo.svg

locale: "en"

collections:
  - label: "Forms"
    name: "forms"
    folder: "src/forms"
    create: true
    fields:
      - label: "Form"
        name: "form"
        widget: "list"
        types:
          - label: "Text Field"
            name: "textfield"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "text" }
              - { label: "Id", name: "id", widget: "string" }
              - { label: "Required", name: "required", widget: "boolean" }
          - label: "Select Field"
            name: "selectfield"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "text" }
              - { label: "Id", name: "id", widget: "string" }
              - { label: "Required", name: "required", widget: "boolean" }
              - label: "Options"
                name: "options"
                widget: "list"
                field: { label: "Option", name: "option", widget: "string" }
